#!/bin/bash

# Interactive configuration script for waybar-weblinks

set -e

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/waybar-weblinks"
CONFIG_FILE="$CONFIG_DIR/links.conf"

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Waybar Web Shortcuts Configuration${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo

if [[ ! -d "$CONFIG_DIR" ]]; then
    echo -e "${YELLOW}Config directory not found. Run install.sh first.${NC}"
    exit 1
fi

echo "This will help you configure your web shortcuts."
echo "Press Enter to keep the current value, or type a new one."
echo

# Initialize arrays
LABELS=()
URLS=()

# Load existing config if it exists
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
    if [[ ${#LINK_LABELS[@]} -gt 0 ]]; then
        LABELS=("${LINK_LABELS[@]}")
        URLS=("${LINK_URLS[@]}")
    fi
fi

# If no existing config, use defaults
if [[ ${#LABELS[@]} -eq 0 ]]; then
    LABELS=("📞 PBX1" "📞 PBX2" "💼 Splynx" "🔧 Omada" "🎫 Helpdesk")
    URLS=("https://pbx1.example.com" "https://pbx2.example.com" "https://portal.example.com/admin" "https://omada.example.com" "https://helpdesk.example.com")
fi

echo "Current shortcuts:"
for i in "${!LABELS[@]}"; do
    echo "  $((i+1)). ${LABELS[$i]} → ${URLS[$i]}"
done
echo

read -p "How many shortcuts do you want? [${#LABELS[@]}] " num_links
num_links=${num_links:-${#LABELS[@]}}

NEW_LABELS=()
NEW_URLS=()

for ((i=0; i<num_links; i++)); do
    echo -e "\n${GREEN}Shortcut $((i+1)):${NC}"
    
    # Get label
    default_label="${LABELS[$i]:-"🔗 Link $((i+1))"}"
    read -p "  Label [${default_label}]: " label
    label=${label:-$default_label}
    NEW_LABELS+=("$label")
    
    # Get URL
    default_url="${URLS[$i]:-"https://example.com"}"
    read -p "  URL [${default_url}]: " url
    url=${url:-$default_url}
    NEW_URLS+=("$url")
done

# Write config file
echo -e "\n${BLUE}Writing configuration...${NC}"
cat > "$CONFIG_FILE" << EOF
# Web Links Configuration
# Generated by configure.sh on $(date)

# Labels (what appears in the menu with emoji icons)
LINK_LABELS=(
EOF

for label in "${NEW_LABELS[@]}"; do
    echo "    \"$label\"" >> "$CONFIG_FILE"
done

cat >> "$CONFIG_FILE" << EOF
)

# URLs (corresponding links that will open)
LINK_URLS=(
EOF

for url in "${NEW_URLS[@]}"; do
    echo "    \"$url\"" >> "$CONFIG_FILE"
done

cat >> "$CONFIG_FILE" << EOF
)
EOF

echo -e "${GREEN}✓ Configuration saved to $CONFIG_FILE${NC}"
echo
echo "Your shortcuts:"
for i in "${!NEW_LABELS[@]}"; do
    echo "  ${NEW_LABELS[$i]} → ${NEW_URLS[$i]}"
done
echo
echo -e "Reload waybar to see changes: ${BLUE}killall waybar && waybar &${NC}"
